[workspace]
resolver = "2"
members = ["imessage-database", "imessage-exporter", "imessage-stats"]

[profile.release]
# Perform Link Time Optimization
lto = true
# Do not unwind stack on crash
panic = "abort"
